---
- hosts: web
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"

  - name: Create OS info file
    ansible.builtin.copy:
     content: "OS Name: {{ ansible_distribution }}\nDistribution Version: {{ ansible_distribution_version }}\n"
     dest: "/home/{{ ansible_facts.user_id}}/{{ ansible_distribution }}.txt"    #{{ ansible_facts.user_id}} = user
    #  dest: "{{ ansible_facts.user_dir }}/{{ ansible_distribution }}.txt"    #{{ ansible_facts.user_dir }} = /home/user

