# Replaced the hardcoded list of packages in playbook to use the values from the "app_list" variable defined in the inventory file.
# ---
# - hosts: all
#   become: yes
#   tasks:
#     - name: Install applications
#       yum:
#         name: "{{ item }}"
#         state: present
#       with_items:
#         - vim
#         - sqlite
#         - jq


---
- hosts: all
  become: yes
  tasks:
    - name: Install applications
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ app_list }}"
