# Add three new variables named car_model, country_name and title under the play and move the values over there. Use these variables within the task to remove the hardcoded values.
# ---
# - hosts: localhost
#   tasks:
#     - command: 'echo "My car is BMW M3"'
#     - command: 'echo "I live in the USA"'
#     - command: 'echo "I work as a Systems Engineer"'


---
- hosts: localhost
  var:
   car_model: 'BMW M3'
   country_name: USA
   title: 'System Engineer'
  tasks:
    - command: 'echo "My car is {{ car_model }}"'
    - command: 'echo "I live in the {{ country_name }}"'
    - command: 'echo "I work as a {{ title }}"'
